FROM node:18-slim as base

RUN npm install -g npm@8
WORKDIR /app
COPY . .


FROM base as dependencies

ARG NPM_TOKEN
RUN npm run setup


FROM base as dev-server

COPY --from=dependencies /app/node_modules /app/node_modules
